<?php

namespace Scourgen\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUserByIdentifiant($identifiant){
       return $this->findBy(array('identifiant'=>$identifiant));
    }

    public function getUserByProfile($profile){
        return $this->findBy(array('profile'=>$profile));
    }
}
